name: money_change
description: A modern money management application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  fl_chart: ^0.60.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_secure_storage: ^8.0.0
  http: ^0.13.5
  flutter_stripe: ^9.4.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
